<a href="https://colab.research.google.com/github/anuragbisht12/NLP/blob/master/Word_Embedding_using_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Word Embedding using Keras

In [0]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [0]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [0]:
### Vocabulary size
voc_size=10000

One hot encoding

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[4406, 9313, 7194, 5394], [4406, 9313, 7194, 6582], [4406, 6025, 7194, 1055], [7576, 1032, 4643, 7853, 723], [7576, 1032, 4643, 7853, 3333], [5030, 4406, 2936, 7194, 2206], [899, 9772, 8216, 7853]]



Word Embedding Represntation

In [0]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4406 9313 7194 5394]
 [   0    0    0    0 4406 9313 7194 6582]
 [   0    0    0    0 4406 6025 7194 1055]
 [   0    0    0 7576 1032 4643 7853  723]
 [   0    0    0 7576 1032 4643 7853 3333]
 [   0    0    0 5030 4406 2936 7194 2206]
 [   0    0    0    0  899 9772 8216 7853]]


In [0]:
dim=10

In [0]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

[[[-0.03375838 -0.04193823 -0.01538657 -0.00054299 -0.04121787
    0.01528071  0.04011699  0.04722268 -0.01648583 -0.00642531]
  [-0.03375838 -0.04193823 -0.01538657 -0.00054299 -0.04121787
    0.01528071  0.04011699  0.04722268 -0.01648583 -0.00642531]
  [-0.03375838 -0.04193823 -0.01538657 -0.00054299 -0.04121787
    0.01528071  0.04011699  0.04722268 -0.01648583 -0.00642531]
  [-0.03375838 -0.04193823 -0.01538657 -0.00054299 -0.04121787
    0.01528071  0.04011699  0.04722268 -0.01648583 -0.00642531]
  [-0.02836992 -0.00936042 -0.01581724  0.01473388  0.04255045
    0.0243547   0.0328395   0.03147743  0.00140514  0.01648187]
  [ 0.02913276  0.00297944 -0.00479703  0.01741011 -0.04549265
   -0.01163305 -0.00839372  0.04707421 -0.02940459  0.02758003]
  [ 0.049126    0.01862682 -0.01490843  0.03749082  0.03337051
   -0.01477922  0.04544866  0.02998969 -0.0143474  -0.00215126]
  [ 0.04080279  0.00444609 -0.02977977 -0.02413747 -0.03841425
    0.03491105 -0.03525437  0.04389674  0.025034

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 4406, 9313, 7194, 5394], dtype=int32)

In [15]:
print(model.predict(embedded_docs)[0])

[[-0.03375838 -0.04193823 -0.01538657 -0.00054299 -0.04121787  0.01528071
   0.04011699  0.04722268 -0.01648583 -0.00642531]
 [-0.03375838 -0.04193823 -0.01538657 -0.00054299 -0.04121787  0.01528071
   0.04011699  0.04722268 -0.01648583 -0.00642531]
 [-0.03375838 -0.04193823 -0.01538657 -0.00054299 -0.04121787  0.01528071
   0.04011699  0.04722268 -0.01648583 -0.00642531]
 [-0.03375838 -0.04193823 -0.01538657 -0.00054299 -0.04121787  0.01528071
   0.04011699  0.04722268 -0.01648583 -0.00642531]
 [-0.02836992 -0.00936042 -0.01581724  0.01473388  0.04255045  0.0243547
   0.0328395   0.03147743  0.00140514  0.01648187]
 [ 0.02913276  0.00297944 -0.00479703  0.01741011 -0.04549265 -0.01163305
  -0.00839372  0.04707421 -0.02940459  0.02758003]
 [ 0.049126    0.01862682 -0.01490843  0.03749082  0.03337051 -0.01477922
   0.04544866  0.02998969 -0.0143474  -0.00215126]
 [ 0.04080279  0.00444609 -0.02977977 -0.02413747 -0.03841425  0.03491105
  -0.03525437  0.04389674  0.02503402 -0.04783752]]
